'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from '../components'
import BookProvider from '../context/BookContext'
import RouteGuard from '../components/RouteGuard'
import { AuthContextProvider } from '../context/AuthContext'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Bookstore',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RouteGuard>
          {/* <AuthContextProvider> */}

          <Header />
          <BookProvider>{children}</BookProvider>
          {/* </AuthContextProvider> */}
        </RouteGuard>
      </body>
    </html>
  )
}
